version: "3"
services:  
  nginx:
    restart: always
    build: ./nginx
    image: nginx
    networks:
      - main
    ports:
      - "8000:8000"
  webex-bot:
    tty: true
    build: .
    networks:
      - main
    volumes:
      - ./app:/app
    ports:
      - "5000"
    env_file: .env
    command: [gunicorn, --bind, 0.0.0.0:8000, wsgi:bot]

networks:
  main:
