version: "3"
services:
  webex-bot:
    tty: true
    build: .
    networks:
      - main
    volumes:
      - ./webexteamsbot:/code/app
    ports:
      - "5000:5000"
    env_file: .env

networks:
  main:
